import './globals.css'
import Header from '@/Components/Header/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <div className='w-screen h-screen grid grid-cols-12 gap-0'>
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
